# Generated by Django 4.1.6 on 2023-02-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='user',
            name='isApprover',
            field=models.BooleanField(default=False, verbose_name='approver status'),
        ),
    ]
