# Generated by Django 4.1.6 on 2023-02-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_isadmin_user_isapprover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isApprover',
        ),
    ]
