# Generated by Django 4.1.6 on 2023-02-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_requested', models.DateField()),
                ('date_closed', models.DateField()),
                ('area', models.IntegerField()),
                ('description', models.CharField(max_length=800)),
                ('is_approved', models.BooleanField()),
                ('is_rejected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField()),
                ('isApprover', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Requests',
            fields=[
                ('row_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_id', models.ManyToManyField(to='change_request.request')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_request.user')),
            ],
        ),
    ]
