# Generated by Django 4.1.6 on 2023-02-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isApprover',
        ),
        migrations.AlterField(
            model_name='request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
