# Generated by Django 4.1.6 on 2023-02-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_request', '0002_remove_user_isadmin_remove_user_isapprover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='area',
            field=models.CharField(choices=[('ETM', 'ETM'), ('CD6R 2pc', 'CD6R 2pc'), ('P702', 'P702'), ('Supermarket', 'Supermarket'), ('LD71', 'LD71')], max_length=20),
        ),
    ]
