# Generated by Django 4.1.6 on 2023-02-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change_request', '0003_area_alter_request_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_requests',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user_requests',
            name='request_id',
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isApprover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_requests',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='change_request.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_requests',
            name='row_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Edit_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.CharField(max_length=800)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_request.request')),
            ],
        ),
        migrations.CreateModel(
            name='Approvers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_request.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_request.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_request.user')),
            ],
        ),
    ]
