# Generated by Django 4.1.6 on 2023-02-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_request', '0004_rename_user_id_user_requests_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Requests',
            new_name='My_Change_Requests',
        ),
    ]
