# Generated by Django 4.1.6 on 2023-02-18 18:32

import change_request.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change_request', '0005_rename_user_requests_my_change_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit_request',
            old_name='request',
            new_name='edit_request',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='description',
            new_name='description_of_change',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='date_closed',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AddField(
            model_name='request',
            name='reason_for_request',
            field=models.CharField(default='Continuous Improvement', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.IntegerField(default='23-00', primary_key=change_request.models.User, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default='Danielle Courtney', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
